baselink = "/"
languageCode = "en-us"
summaryLength = "10"
theme = "imbizo-website-base"
title = "#isiCNI - Computational Neuroscience Imbizo"
[[menu.main]]
link = "about"
name = "About"
weight = 2
[[menu.main]]
link = "blog"
name = "Blog"
weight = 3
[[menu.main]]
link = "portfolio"
name = "Portfolio"
weight = 4
[[menu.main]]
link = "contact"
name = "Contact"
weight = 5
[params]
address = "Cape Town, South Africa"
author = "Christopher Currin"
copyright = "Copyright &copy; Imbizo"
description = "IBRO Simons Computational Neuroscience Imbizo summer school in Cape Town, South Africa"
email = "isicn.imbizo@gmail.com"
google_analitycs_id = "Your ID"
home = "Home"
logo = "images/imbizo_sticker2020.png"
phone = ""
theme_color = "#26AE60"
[params.contact]
enable = true
form_action = "#"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
link = "#"
icon = "ti-facebook"
[[params.social]]
link = "#"
icon = "ti-instagram"
[[params.social]]
link = "#"
icon = "ti-dribbble"
[[params.social]]
link = "#"
icon = "ti-twitter-alt"
