---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: data/homepage.yml
  label: Homepage
- type: document
  path: data/sponsors.yml
  label: Sponsors
- type: heading
  label: Application
- type: document
  path: content/apply/_index.md
  label: Application info page header
- type: document
  path: data/application_info.yml
  label: Application Info
- type: heading
  label: Archive
- type: document
  path: content/archive/_index.md
  label: Archive page header
- type: directory
  path: content/archive
  label: Past years
  create: all
  match: "**/*"
  exclude: _index.md
- type: heading
  label: People
- type: document
  path: content/people/_index.md
  label: People page header
- type: document
  path: data/faculty.yml
  label: Faculty
- type: document
  path: data/tutors.yml
  label: Teaching assistants
- type: heading
  label: Other
- type: directory
  path: content/news
  label: News
  create: all
  match: "*"
  exclude: _index.md
  templates:
  - post
- type: directory
  path: content/contact
  label: Contact
  create: none
  match: "*"
- type: document
  path: config.toml
  label: Configuration
- type: directory
  path: content
  label: Content
  create: all
  match: "**/*"
  templates:
  - page-header-and-content
- type: directory
  path: data
  label: Data
  create: documents
  match: "*"
  new_doc_ext: yml
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.80.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.81.0
