---
label: Application Info data
hide_body: true
fields:
- type: text
  name: link
  label: link
  default: "/apply"
  description: link to application page. default /apply
- type: text
  name: info_link_label
  label: info link label
  description: e.g. Application info
- type: field_group_list
  name: applications
  label: applications
  fields:
  - name: heading
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: false
      schema:
        format: markdown
    label: heading
    description: text to go above the button
  - type: text
    name: label
    label: Button label
  - type: boolean
    name: open
    label: open
  - type: text
    name: closed_message
    label: closed message
    description: only appears when closed
  - type: text
    name: URL
    label: URL
    description: add link to a form here
  - type: text
    name: open_date
    label: open date
    description: rough estimate (hence text field) on when application will open
  - type: datetime
    name: close_date
    label: close date
    description: exact expected date for which this application should be closed
  - type: text
    name: acceptance_date
    label: acceptance date
    description: when acceptances will be announced...
  description: All possible applications (e.g. students, TAs, abstract submissions)
    go here.<br>Each application can be independently open and have unique close dates.
  config:
    labelField: label
- type: field_group
  name: all_applications_period
  label: all applications period
  fields:
  - name: show_period
    type: boolean
    label: show application period
    description: whether to show a broad application period. useful when there are
      multiple applications. False otherwise
  - name: period_text
    type: text
    config:
      required: false
    label: application period heading
    description: Heading for application period<br>e.g. Registration period
  - type: text
    name: applications_open_date
    label: applications_open_date
  - type: datetime
    name: applications_close_date
    label: applications_close_date
  - type: text
    name: acceptance_date
    label: acceptance_date
  description: display application period for all applications. <br>disable when there
    is only one application
- type: field_group
  name: target_applicants
  label: target_applicants
  fields:
  - type: boolean
    name: enable
    label: enable
  - type: text
    name: title
    label: title
  - type: textarea
    name: content
    label: content
  - type: text
    name: preamble
    label: preamble
  - type: field_group_list
    name: item
    label: item
    fields:
    - type: text
      name: title
      label: title
    - type: file
      name: icon
      label: icon
    - type: textarea
      name: content
      label: content
- type: field_group
  name: team
  label: team
  fields:
  - type: boolean
    name: enable
    label: enable
  - type: text
    name: title
    label: title
  - type: field_group_list
    name: team_member
    label: team_member
    fields:
    - type: text
      name: title
      label: title
    - type: file
      name: image
      label: image
    - type: text
      name: designation
      label: designation
- type: field_group
  name: faq
  label: faq
  fields:
  - type: boolean
    name: enable
    label: enable
  - type: text
    name: title
    label: title
  - type: number
    name: gapsize
    label: gapsize
  - type: field_group_list
    name: item
    label: item
    fields:
    - type: text
      name: question
      label: question
    - type: textarea
      name: answer
      label: answer
